apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elastic-tls
  namespace: envoy-gateway-system
spec:
  issuerRef:
    name: vault-gateway-issuer
    kind: ClusterIssuer
  secretName: elastic-tls-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  commonName: elastic.ilysium.io
  dnsNames:
    - elastic.ilysium.io
  usages:
    - server auth
    - client auth
