apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: envoy-gateway-system
spec:
  issuerRef:
    name: vault-gateway-issuer
    kind: ClusterIssuer
  secretName: vault-tls-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  commonName: vault.ilysium.io
  dnsNames:
    - vault.ilysium.io
  usages:
    - server auth
    - client auth
