apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: ilysium-root-ca
spec:
  sources:
    - inLine: |
        -----BEGIN CERTIFICATE-----
        MIIBdzCCAR2gAwIBAgIQdr3VnpzGvx7U4pzHMvlKOjAKBggqhkjOPQQDAjAaMRgw
        FgYDVQQDEw9JbHlzaXVtIFJvb3QgQ0EwHhcNMjYwNDI3MDAzNzAzWhcNMzYwNDI0
        MDAzNzAzWjAaMRgwFgYDVQQDEw9JbHlzaXVtIFJvb3QgQ0EwWTATBgcqhkjOPQIB
        BggqhkjOPQMBBwNCAATOgCR0VriwrWvwxe9m91vMVmhG9gQlmGtVsr+1p9fxmdnm
        7sgLGTOK7YnlvY8nivKDfMk33zMkS+XOLzezLdDpo0UwQzAOBgNVHQ8BAf8EBAMC
        AQYwEgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQUZiBt/1Q6yZDUQN9TVI9p
        wwVQVOgwCgYIKoZIzj0EAwIDSAAwRQIgJSuDlHwdZaeqjJMzba+Cz4zKEPA3lBon
        K99A5+jSojwCIQDNNoDxzGCzvIaiJ/5jGj/o1NSOHJym/4MXaAufjXgX1A==
        -----END CERTIFICATE-----
  target:
    configMap:
      key: ca.crt
    namespaceSelector: {}
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: system-cas
spec:
  sources:
    - useDefaultCAs: true # system roots
  target:
    configMap:
      key: ca-bundle.crt
    namespaceSelector: {}
