apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 5m
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  serviceAccountName: flux
  targetNamespace: external-secrets
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: "2.3.x"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 12h
  releaseName: external-secrets
  # https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/values.yaml
  values:
    podLabels:
      blackquartz.io/app: "external-secrets"
      blackquartz/io/env: ${ENVIRONMENT}
