apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: platform-gateway
  namespace: envoy-gateway-system
spec:
  gatewayClassName: cluster-gateway
  listeners:
    - name: vault-http
      hostname: vault.blackquartz.io
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: elastic-http
      hostname: elastic.blackquartz.io
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All

