apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: platform-gateway
  namespace: envoy-gateway-system
spec:
  gatewayClassName: cluster-gateway
  listeners:
    - name: vault-https
      protocol: HTTPS
      port: 443
      hostname: vault.ilysium.io
      tls:
        certificateRefs:
          - name: vault-tls-secret
      allowedRoutes:
        namespaces:
          from: All
    - name: elastic-https
      protocol: HTTPS
      port: 443
      hostname: elastic.ilysium.io
      tls:
        certificateRefs:
          - name: elastic-tls-secret
      allowedRoutes:
        namespaces:
          from: All
    - name: elasticsearch-https
      protocol: HTTPS
      port: 443
      hostname: elasticsearch.ilysium.io
      tls:
        certificateRefs:
          - name: elasticsearch-tls-secret
      allowedRoutes:
        namespaces:
          from: All
